name = "Flowergarden"
author = "senare"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6f2fa76e6c87b16d48f3b76a70043820935efe9071204146b413e4a6f85d119"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
