name = "Flowergarden"
author = "senare"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c2049d3357717b226d1c6b9d9dce8022422b038ab133d614779d5a311e11765"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
