name = "Flowergarden"
author = "senare"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9df1449b0e2e58ec761213c3a4a8e3e22472ef5e3177fc0567f43eaf8664240d"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
